# Generated by Django 4.1.2 on 2022-11-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aldshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='buddy', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('kerala', 'KERALA'), ('tamil_nadu', 'TAMIL NADU'), ('karnadaka', 'KARNADAKA')], default='kerala', max_length=20)),
                ('pincode', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('alt_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer_percentage', models.CharField(default=0, max_length=100)),
                ('image', models.ImageField(upload_to='Category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image_1', models.ImageField(upload_to='image_2_of_products')),
                ('image_2', models.ImageField(upload_to='image_2_of_products')),
                ('image_3', models.ImageField(upload_to='image_3_of_products')),
                ('image_4', models.ImageField(upload_to='image_4_of_products')),
                ('arrival_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=300)),
                ('stock_available', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('total_sold', models.IntegerField()),
                ('is_trusted', models.CharField(choices=[('trusted', 'Trusted'), ('not_trusted', 'Not Trusted')], default='trusted', max_length=20)),
                ('available_status', models.CharField(choices=[('availabe', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('offer_percentage', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_day', models.CharField(default=18, max_length=100)),
                ('Order_month', models.CharField(default=11, max_length=100)),
                ('Order_year', models.CharField(default=2022, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='ordered', max_length=100)),
                ('Address', models.CharField(default=1, max_length=20)),
                ('payment_method', models.CharField(default='cod', max_length=20)),
                ('total_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aldshop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aldshop.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.CharField(default=0, max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aldshop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aldshop.users')),
            ],
        ),
    ]
