# Generated by Django 4.1.2 on 2022-11-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldshop', '0002_address_banners_category_products_orders_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cropped_images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=20, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=20, max_length=50),
        ),
    ]
