# Generated by Django 4.1.2 on 2022-11-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldshop', '0004_delete_image_cart_guest_id_alter_orders_order_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=23, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=23, max_length=50),
        ),
    ]
