# Generated by Django 4.1.2 on 2022-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldshop', '0006_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_month',
            field=models.CharField(default=12, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_month',
            field=models.CharField(default=12, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('contact_number', 'email')},
        ),
    ]
