# Generated by Django 4.1.2 on 2022-12-03 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aldshop', '0008_coupon_coupon_history_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturing_date',
            field=models.CharField(default=datetime.date(2022, 12, 3), max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=3, max_length=50),
        ),
    ]
